"""Built-in policy scaffolding for ``llm-thorn init``.

The pip package ships no policy files (the templates under ``policies/`` live
at the repo root, outside the wheel), so a fresh ``pip install`` would leave a
user with the CLI but nothing to pass to ``--policy``. ``llm-thorn init`` writes
:data:`STARTER_POLICY` to disk so the very first run works with zero hand-editing
and no local Ollama.
"""

from __future__ import annotations

#: A ready-to-run starter policy. Heuristic + context + output layers need no
#: external services; the semantic and safety layers (which call a local Ollama)
#: are disabled by default so this works on any fresh machine.
STARTER_POLICY = """\
# Thorn starter policy — generated by `llm-thorn init`.
#
# Runs with zero local setup. The semantic (layer 2) and safety (layer 5)
# layers call a local Ollama (https://ollama.com); they are disabled below so
# this policy works on any machine. Once Ollama is running, flip them to true.
policy:
  name: starter
  version: 1.0.0
  description: Ready-to-run starter policy (no Ollama required).

  layers:
    heuristic: true
    semantic: false     # needs a local Ollama — set true to classify intent
    context: true
    output: true
    safety: false       # needs a local Ollama — set true to judge response harm

  rules:
    # High-confidence signature attacks are blocked outright.
    - id: block-known-attacks
      description: Block inputs matching high-confidence attack signatures.
      layer: heuristic
      condition:
        verdict: malicious
        confidence_above: 0.8
      action: block
      alert: true

    # Softer matches are logged but allowed — real traffic brushes patterns.
    - id: warn-soft-signatures
      description: Log low-confidence signature matches for tuning.
      layer: heuristic
      condition:
        verdict: suspicious
        confidence_above: 0.5
      action: warn

    # Multi-turn social engineering: block once the trajectory is clear.
    - id: block-escalating-sessions
      description: Block sessions whose accumulated risk indicates probing.
      layer: context
      condition:
        verdict: malicious
        confidence_above: 0.6
      action: block
      alert: true

    # Never deliver a response that leaked the system prompt or broke character.
    - id: block-compromised-output
      description: Block responses showing successful injection or prompt leakage.
      layer: output
      condition:
        verdict: malicious
        confidence_above: 0.8
      action: block
      alert: true

    # PII in responses gets redacted, not blocked — the rest is still useful.
    - id: redact-pii-in-responses
      description: Strip emails, phone numbers, SSNs, and card numbers from output.
      layer: output
      condition:
        verdict: suspicious
        confidence_above: 0.5
      action: redact

  defaults:
    on_layer_error: allow      # fail-open; flip to `block` for fail-closed
    max_session_turns: 50
    session_ttl_seconds: 3600
"""
